### ISSUE TITLE
Static type hinting not working in PyCharm or IntelliJ

### ISSUE THREAD

**Issue by christianplatta1012** [JamesHutchison/megamock#125]
Hi,
can you explain, why the type hinting is only working in VC Code and not in PyCharm or IntelliJ?

When I type the following code, "mock_instance" won't get any type hinting  in PyCharm or IntelliJ. It works in VS Code.
Is this a configuration problem?

def test_mega_mocking():
    patch = MegaPatch.it(ClassICareAbout)
    mock_instance = patch.megainstance
    mock_instance.hello.return_value = "some value"
    
  Best regards,
  Christian

**Comment by JamesHutchison** [comment]
Hey thanks for bringing this to my attention! I can reproduce your issue an I have a preliminary fix. You can add an overload with the type hinting and that seems to fix the behavior, however mypy starts to complain about `return_value`.

```python
    @overload  # type: ignore
    @staticmethod
    def it(  # type: ignore
        spec: type[T] | None = None,
        *,
        spec_set: bool = True,
        side_effect: Any = None,
        return_value: Any = MISSING,
        _wraps_mock: (
            mock.Mock
            | mock.MagicMock
            | mock.NonCallableMock
            | mock.NonCallableMagicMock
            | None
        ) = None,
        _parent_mega_mock: _MegaMockMixin | None = None,
        **kwargs,
    ) -> T | MegaMock[T, MegaMock | T]:
        ...
```

I'll need to dig into this more to. Unfortunately Python doesn't have an intersection type, so this functions by doing some hackiness to return a union that VS Code understood to be a union while mypy was interpreting it as an `Any`. It appears that PyCharm also was using `Any`

If you're not using mypy and would like this functioning today, you can modify the file inside the virtual environment to add the overload with the type definition and that should provide the functionality. Here's another example with `the_class`

```python
    @overload  # type: ignore
    @staticmethod
    def the_class(  # type: ignore
        spec: type[T], *, spec_set: bool = True, **kwargs
    ) -> type[T] | MegaMock[type[T], MegaMock[Any, Any] | T]:
        ...

    @staticmethod
    def the_class(spec: type[T], *, spec_set: bool = True, **kwargs):
       # the rest of the code that's already there
```

**Comment by JamesHutchison** [comment]
I'm away from my computer but it occurred to me that adding the return type might be equivalent to adding the overload.

**Comment by JamesHutchison** [comment]
@christianplatta1012 I pushed version beta-10 which should fix the issue. Please feel free to reopen if it's still not working for you.

`pip install --upgrade megamock`

**Comment by christianplatta1012** [comment]
Hi, unfortunately it is still showing only a generic type "U" in PyCharm and Idea Ultimate. I've created a new project from scratch and installed version 0.1.0b10 
![megamock_type_pycharm](https://github.com/JamesHutchison/megamock/assets/41356388/fb69188f-a5d7-40d7-8a80-1cbaa652d68d)

**Comment by christianplatta1012** [comment]
I've wrote some very simplistic test code with the Union Type and this works for IntelliJ:

`from typing import Union,TypeVar

T = TypeVar('T')
def merged_types(x: T) -> Union[str, T]:
    if x:
        return "x"
    else:
        return x

def test_union_types():
    x= merged_types(ClassICareAbout())` 
    
x autocompletes with all methods from str and ClassICareAbout.
Don't know if this is of any help for finding the problem in megamock though :-/

**Comment by JamesHutchison** [comment]
Thanks for letting me know that it wasn't fully fixed! I was able to reproduce the issue and I just pushed out a new version that fixes that problem. It's worth calling out that if you do something like `patch.megainstance.some_method.return_value = 5`, the autocompletion won't show up for `return_value` because the static type checking treats `some_method` as a function object.

Please LMK if you find any other issues!

**Comment by christianplatta1012** [comment]
It works now, thank you for you quick response and help!
